/* parametry.h */ 

//PRZERWY CZASOWE 
#define CZAS_PAUZY_1		100
#define CZAS_PAUZY_2		200
#define CZAS_PAUZY_3		400


//pozycje kursora
//------------------------------------------------------------------------------

//G£ÓWNA POZYCJA OKIENKA
#define POZYCJA_OKIENKA_1		829, 53

//PUSTE POLE SAP 1
#define PUSTE_POLE_SAP_1		500, 500

//PUSTE POLE SAP 2
#define PUSTE_POLE_SAP_2		1400, 400

//TWORZENIE MATERIA£U - SORTOWANIE
#define TWORZENIE_MATERIALU_SORTOWANIE		1480, 150

//TWORZENIE MATERIA£U - SORTOWANIE MALEJ¥CE
#define TWORZENIE_MATERIALU_SORTOWANIE_MALEJACE		1480, 370

//KLASYFIKACJA - ZAZNACZANIE KLASY
#define KLASYFIKACJA_ZAZNACZANIE_KLASY  790, 270

//KLASYFIKACJA - USUWANIE KLASY
#define KLASYFIKACJA_USUWANIE_KLASY  945, 350

//PROFIL KONFIGURACJI - WYBÓR OBIEKTÓW KONFIGUROWALNYCH
#define PROFIL_KONFIGURACJI_WYBOR_OBIEKTOW_KONFIGUROWALNYCH		900, 283	

//ZMIANA SPECYFIKACJI - ZAK£ADKA DOKUMENT
#define ZMIANA_SPECYFIKACJI_ZAKLADKA_DOKUMENT		920, 255

//ZMIANA MATERIA£U - ZAK£ADKA DOKUMENT POZYCJA
#define ZMIANA_MATERIALU_ZAKLADKA_DOKUMENT_POZYCJA		818, 312

//TWORZENIE DOKUMENTACJI - POTWIEDZENIE ARCHIWIZACJI
#define TWORZENIE_DOKUMENTACJI_POTWIEDZENIE_ARCHIWIZACJI		1250, 710	


//------------------------------------------------------------------------------


//rozpoznawanie koloru
//------------------------------------------------------------------------------

//PASEK POLA G£OWNEGO
#define PASEK_POLA_GLOWNEGO_OS_X		960
#define PASEK_POLA_GLOWNEGO_OS_Y		0

//SZARA STRZA£KA POLA G£OWNEGO
#define STRZALKA_POLA_GLOWNEGO_OS_X		1285
#define STRZALKA_POLA_GLOWNEGO_OS_Y		150

//ZIELONY ZNACZEK POLA G£OWNEGO  
#define ZNACZEK_POLA_GLOWNEGO_OS_X      975
#define ZNACZEK_POLA_GLOWNEGO_OS_Y      1003	


//------------------------------------------------------------------------------


//TWORZENIE MATERIA£U - SZUKANIE
#define TWORZENIE_MATERIALU_SZUKANIE_OS_X		1500
#define TWORZENIE_MATERIALU_SZUKANIE_OS_Y		220

//TWORZENIE MATERIA£U - SZUKANIE INDEKSU 1
#define TWORZENIE_MATERIALU_SZUKANIE_INDEKSU_1_OS_X		1500
#define TWORZENIE_MATERIALU_SZUKANIE_INDEKSU_1_OS_Y		960

//TWORZENIE MATERIA£U - SZUKANIE INDEKSU 2
#define TWORZENIE_MATERIALU_SZUKANIE_INDEKSU_2_OS_X		1500
#define TWORZENIE_MATERIALU_SZUKANIE_INDEKSU_2_OS_Y		10

//TWORZENIE MATERIA£U - WYBÓR WGL¥DÓW
#define TWORZENIE_MATERIALU_WYBOR_WGLADOW_OS_X		1500
#define TWORZENIE_MATERIALU_WYBOR_WGLADOW_OS_Y		240

//TWORZENIE MATERIA£U - POZIOMY ORGANIZACYJNE
#define TWORZENIE_MATERIALU_POZIOMY_ORGANIZACYJNE_OS_X		1500
#define TWORZENIE_MATERIALU_POZIOMY_ORGANIZACYJNE_OS_Y		210

//TWORZENIE MATERIA£U - DANE PODSTAWOWE 1
#define TWORZENIE_MATERIALU_DANE_PODSTAWOWE_1_OS_X		1150
#define TWORZENIE_MATERIALU_DANE_PODSTAWOWE_1_OS_Y		190	

//TWORZENIE MATERIA£U - HIERARCHIA PRODUKTU
#define TWORZENIE_MATERIALU_HIERARCHIA_PRODUKTU_OS_X		1400
#define TWORZENIE_MATERIALU_HIERARCHIA_PRODUKTU_OS_Y		440	

//TWORZENIE MATERIA£U - DANE PODSTAWOWE PROD
#define TWORZENIE_MATERIALU_DANE_DODATKOWE_PROD_1_OS_X		1365
#define TWORZENIE_MATERIALU_DANE_DODATKOWE_PROD_1_OS_Y		190	
		
//TWORZENIE MATERIA£U - KLASYFIKACJA - USUWANIE MATERIA£U
#define TWORZENIE_MATERIALU_KLASYFIKACJA_USUWANIE_MATERIALU_OS_X		1500
#define TWORZENIE_MATERIALU_KLASYFIKACJA_USUWANIE_MATERIALU_OS_Y		320			
				
//TWORZENIE MATERIA£U - MRP1
#define TWORZENIE_MATERIALU_MRP1_OS_X		1225
#define TWORZENIE_MATERIALU_MRP1_OS_Y		190	

//TWORZENIE MATERIA£U - DZIA£ SPRZEDA¯Y 1 1
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_1_1_OS_X		1290
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_1_1_OS_Y		190	

//TWORZENIE MATERIA£U - DZIA£ SPRZEDA¯Y 1 1
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_1_2_OS_X		1260
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_1_2_OS_Y		190	

//TWORZENIE MATERIA£U - DZIA£ SPRZEDA¯Y 2
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_2_OS_X		1340
#define TWORZENIE_MATERIALU_DZIAL_SPRZEDAZY_2_OS_Y		190

//TWORZENIE MATERIA£U - ZAPISANIE
#define TWORZENIE_MATERIALU_ZAPISANIE_OS_X		1500
#define TWORZENIE_MATERIALU_ZAPISANIE_OS_Y		320			

//ZMIANA MATERIA£U - DANE DODATKOWE
#define ZMIANA_MATERIALU_DANE_DODATKOWE_OS_X		1500
#define ZMIANA_MATERIALU_DANE_DODATKOWE_OS_Y		290		

//ZMIANA MATERIA£U - DANE DODATKOWE - DANE DOKUMENTU
#define ZMIANA_MATERIALU_DANE_DODATKOWE_DANE_DOKUMENTU_OS_X		1500
#define ZMIANA_MATERIALU_DANE_DODATKOWE_DANE_DOKUMENTU_OS_Y		390	

//ZMIANA MATERIA£U - DANE DODATKOWE - DANE DOKUMENTU - ZAPIS
#define ZMIANA_MATERIALU_DANE_DODATKOWE_DANE_DOKUMENTU_ZAPIS_OS_X		1361
#define ZMIANA_MATERIALU_DANE_DODATKOWE_DANE_DOKUMENTU_ZAPIS_OS_Y		423



//------------------------------------------------------------------------------


//TWORZENIE SPECYFIKACJI MATERIA£OWEJ - KOPIOWANIE WZORCA
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_KOPIOWANIE_WZORCA_OS_X		1350
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_KOPIOWANIE_WZORCA_OS_Y		340	

//TWORZENIE SPECYFIKACJI MATERIA£OWEJ - WZORZEC
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_WZORZEC_OS_X		1350
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_WZORZEC_OS_Y		315	

//TWORZENIE SPECYFIKACJI MATERIA£OWEJ
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_OS_X		1350
#define TWORZENIE_SPECYFIKACJI_MATERIALOWEJ_OS_Y		315	

//ZMIANA SPECYFIKACJI MATERIA£OWEJ
#define ZMIANA_SPECYFIKACJI_MATERIALOWEJ_OS_X		1600
#define ZMIANA_SPECYFIKACJI_MATERIALOWEJ_OS_Y		390	


//------------------------------------------------------------------------------


//TWORZENIE DOKUMENTACJI
#define TWORZENIE_DOKUMENTACJI_OS_X		1462
#define TWORZENIE_DOKUMENTACJI_OS_Y		215

//TWORZENIE DOKUMENTACJI - NOWA WERSJA
#define TWORZENIE_DOKUMENTACJI_NOWA_WERSJA_OS_X		1700
#define TWORZENIE_DOKUMENTACJI_NOWA_WERSJA_OS_Y		320	

//TWORZENIE DOKUMENTACJI - WYBÓR OBIEKTU
#define TWORZENIE_DOKUMENTACJI_WYBOR_OBIEKTU_OS_X		1400
#define TWORZENIE_DOKUMENTACJI_WYBOR_OBIEKTU_OS_Y		340	

//TWORZENIE DOKUMENTACJI - DANE PODSTAWOWE
#define TWORZENIE_DOKUMENTACJI_DANE_PODSTAWOWE_OS_X		1700
#define TWORZENIE_DOKUMENTACJI_DANE_PODSTAWOWE_OS_Y		320	

//TWORZENIE DOKUMENTACJI - USUWANIE DOKUMENTACJI
#define TWORZENIE_DOKUMENTACJI_USUWANIE_DOKUMENTACJI_OS_X		1640
#define TWORZENIE_DOKUMENTACJI_USUWANIE_DOKUMENTACJI_OS_Y		320	

//TWORZENIE DOKUMENTACJI - USUWANIE DOKUMENTACJI
#define TWORZENIE_DOKUMENTACJI_USUWANIE_DOKUMENTACJI_INFORMACJA_OS_X		1550
#define TWORZENIE_DOKUMENTACJI_USUWANIE_DOKUMENTACJI_INFORMACJA_OS_Y		520	

//TWORZENIE DOKUMENTACJI - OTWIERANIE PLIKU
#define TWORZENIE_DOKUMENTACJI_OTWIERANIE_PLIKU_OS_X		1600
#define TWORZENIE_DOKUMENTACJI_OTWIERANIE_PLIKU_OS_Y		60	

//TWORZENIE DOKUMENTACJI - DODANIE PLIKU
#define TWORZENIE_DOKUMENTACJI_DODANIE_PLIKU_OS_X		1700
#define TWORZENIE_DOKUMENTACJI_DODANIE_PLIKU_OS_Y		890	

//ZMIANA DOKUMENTACJI - EKRAN POCZ¥TKOWY
#define ZMIANA_DOKUMENTACJI_EKRAN_POCZATKOWY_OS_X		976
#define ZMIANA_DOKUMENTACJI_EKRAN_POCZATKOWY_OS_Y		190

//ZMIANA DOKUMENTACJI
#define ZMIANA_DOKUMENTACJI_OS_X		1462
#define ZMIANA_DOKUMENTACJI_OS_Y		215

//TWORZENIE DOKUMENTACJI - ARCHIWUM ORYGINA£U
#define TWORZENIE_DOKUMENTACJI_ARCHIWUM_ORYGINALU_OS_X		1500
#define TWORZENIE_DOKUMENTACJI_ARCHIWUM_ORYGINALU_OS_Y		890	

//------------------------------------------------------------------------------


// kolory do rozpoznania

//SZARY 1
#define KOLOR_SZARY_1_RGB_1		a != 234 and b != 237 and c != 240

//SZARY 2 - PRZYCISK STRZA£KI
#define KOLOR_SZARY_2_RGB_1		a != 102 and b != 102 and c != 102
#define KOLOR_SZARY_2_RGB_2		a == 102 and b == 102 and c == 102

//SZARY 3
#define KOLOR_SZARY_3_RGB_1		a != 247 and b != 247 and c != 247

//SZARY 4
#define KOLOR_SZARY_4_RGB_1		a != 229 and b != 229 and c != 229

//SZARY 5
#define KOLOR_SZARY_5_RGB_1		a != 249 and b != 249 and c != 249

//SZARY 6
#define KOLOR_SZARY_6_RGB_1		a != 236 and b != 236 and c != 236

//SZARY 7
#define KOLOR_SZARY_7_RGB_1		a != 242 and b != 242 and c != 242

//ZIELONY - IKONA
#define KOLOR_ZIELONY_1_RGB_1		a != 0 and b != 139 and c != 0

//NIEBIESKI
#define KOLOR_NIEBIESKI_1_RGB_1		a != 0 and b != 157 and c != 224

//NIEBIESKI
#define KOLOR_NIEBIESKI_1_RGB_2		a == 0 and b == 157 and c == 224

//NIEBIESKI
#define KOLOR_NIEBIESKI_2_RGB_1	a != 188 and b != 226 and c != 247

//NIEBIESKI
#define KOLOR_NIEBIESKI_2_RGB_2	a == 188 and b == 226 and c == 247

//BIA£Y
#define KOLOR_BIALY_1_RGB_1		a != 255 and b != 255 and c != 255

//CZERWONY
#define KOLOR_CZERWONY_1_RGB_1		a != 189 and b != 0 and c != 0



